---
- name: Backup cisco configurations
  hosts: appc_cisco_mgmt_sw 
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: ios

  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars
      delegate_to: localhost

  tasks:
    - name: "Backup running configs to Gitlab repo => {{ config_backup_git_repo_name }}"
      ansible.builtin.import_role:
        name: role-cisco-config-backup
      vars:
        backup: true
        tmp_root_dir: "{{ root_dir }}"
        vendor_dir: "{{ config_backup_git_repo_cisco_dir }}"
        git_repo_name: "{{ config_backup_git_repo_name }}"
        git_repo_url: "{{ config_backup_git_repo_url }}"
        git_repo_branch: "{{ config_backup_git_repo_branch }}"
        git_user: "{{ git_user }}"
        git_user_email: "{{ git_user_email }}"