---
# Cisco configs backup tasks
# - name: TEST - show ip int brief
#   cisco.ios.ios_command:
#     commands: show ip int brief
#   register: cisco_int_output

# - name: TEST - Display interface status
#   ansible.builtin.debug:
#     var: cisco_int_output['stdout_lines']

- name: Collect cisco device running configs
  cisco.ios.ios_command:
    commands: show running-config
  register: config_output

# regex_replace('\r\n', '\n'): Ensures that the configuration is formatted properly with new lines,
# in case the original output contains carriage return and line feed (\r\n).
- name: Ensure the config is properly formatted
  ansible.builtin.set_fact:
    formatted_config: "{{ config_output.stdout[0] | regex_replace('\r\n', '\n') }}"
  delegate_to: localhost

- name: Save the configuration to the temporary config store
  ansible.builtin.copy:
    content: "{{ formatted_config }}"
    dest: "{{ tmp_config_store }}"
  delegate_to: localhost

